[package]
name = "aoc_09"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winnow = "0.6.20"

[dev-dependencies]
proptest = "1.5.0"
proptest-derive = "0.5.0"